name: ~Deploy Container App

on:
  workflow_call:
    inputs:
      environment_name:
        required: true
        type: string
    outputs:
      url:
        value: ${{ jobs.deploy.outputs.url }}

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment_name }}
      url: ${{ steps.get-url.outputs.url }}
    outputs:
      url: ${{ steps.get-url.outputs.url }}

    steps:
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: Verify Container App
        id: get-url
        run: |
          url=$(az containerapp show \
            -n ${{ vars.PROJECT_NAME }}-${{ inputs.environment_name }}-app \
            -g ${{ vars.PROJECT_NAME }}-${{ inputs.environment_name }}-rg \
            --query "properties.configuration.ingress.fqdn" -o tsv)
          echo "url=https://$url" >> $GITHUB_OUTPUT

      - name: Deploy to Container App
        uses: azure/container-apps-deploy-action@v2
        with:
          disableTelemetry: true
          containerAppName: ${{ vars.PROJECT_NAME }}-${{ inputs.environment_name }}-app
          resourceGroup: ${{ vars.PROJECT_NAME }}-${{ inputs.environment_name }}-rg
          imageToDeploy: ${{ vars.ACR_NAME }}.azurecr.io/app:${{ github.sha }}
